config/routes.rb
Carwash::Application.routes.draw do

  resources :memberships

  resources :cars

  get "dashboards/index"

  resources :inventories

  resources :type_of_cleaning_and_washings

  resources :customers do 
    member do
      get 'pay'
    end
    collection do 
      put 'dynamic_pricing'
      put 'dynamic_price_member'
    end
  end

  authenticated :user do
    root :to => 'dashboards#index' 
  end
  root :to => "home#index"
   
  devise_for :users do
    delete 'logout' => 'devise/sessions#destroy'
  end
  
  resources :users

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :name, :price
  has_many :customers
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.json
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(params[:membership])

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render json: @membership, status: :created, location: @membership }
      else
        format.html { render action: "new" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= simple_form_for(@membership) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.name %></td>
    <td><%= membership.price %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @membership.name %>
</p>

<p>
  <b>Price:</b>
  <%= @membership.price %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>