config/routes.rb
Carwash::Application.routes.draw do

  resources :memberships

  resources :cars

  get "dashboards/index"

  resources :inventories

  resources :type_of_cleaning_and_washings

  resources :customers do 
    member do
      get 'pay'
    end
    collection do 
      put 'dynamic_pricing'
      put 'dynamic_price_member'
    end
  end

  authenticated :user do
    root :to => 'dashboards#index' 
  end
  root :to => "home#index"
   
  devise_for :users do
    delete 'logout' => 'devise/sessions#destroy'
  end
  
  resources :users

end

app/models/type_of_cleaning_and_washing.rb
class TypeOfCleaningAndWashing < ActiveRecord::Base
  attr_accessible :mem_price, :name, :price, :car_id
  
  has_many :customers
  belongs_to :car, :class_name => "Car", :foreign_key => "car_id"
end

app/controllers/type_of_cleaning_and_washings_controller.rb
class TypeOfCleaningAndWashingsController < ApplicationController
  # GET /type_of_cleaning_and_washings
  # GET /type_of_cleaning_and_washings.json
  def index
    @search = TypeOfCleaningAndWashing.ransack(params[:q])
    @type_of_cleaning_and_washings = @search.result
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.new
  end

  # GET /type_of_cleaning_and_washings/1
  # GET /type_of_cleaning_and_washings/1.json
  def show
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type_of_cleaning_and_washing }
    end
  end

  # GET /type_of_cleaning_and_washings/new
  # GET /type_of_cleaning_and_washings/new.json
  def new
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type_of_cleaning_and_washing }
    end
  end

  # GET /type_of_cleaning_and_washings/1/edit
  def edit
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.find(params[:id])
  end

  # POST /type_of_cleaning_and_washings
  # POST /type_of_cleaning_and_washings.json
  def create
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.new(params[:type_of_cleaning_and_washing])

    respond_to do |format|
      if @type_of_cleaning_and_washing.save
        format.html { redirect_to type_of_cleaning_and_washings_path, notice: 'Type of cleaning and washing was successfully created.' }
        format.json { render json: @type_of_cleaning_and_washing, status: :created, location: @type_of_cleaning_and_washing }
      else
        format.html { render action: "new" }
        format.json { render json: @type_of_cleaning_and_washing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /type_of_cleaning_and_washings/1
  # PUT /type_of_cleaning_and_washings/1.json
  def update
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.find(params[:id])

    respond_to do |format|
      if @type_of_cleaning_and_washing.update_attributes(params[:type_of_cleaning_and_washing])
        format.html { redirect_to type_of_cleaning_and_washings_path, notice: 'Type of cleaning and washing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type_of_cleaning_and_washing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_of_cleaning_and_washings/1
  # DELETE /type_of_cleaning_and_washings/1.json
  def destroy
    @type_of_cleaning_and_washing = TypeOfCleaningAndWashing.find(params[:id])
    @type_of_cleaning_and_washing.destroy

    respond_to do |format|
      format.html { redirect_to type_of_cleaning_and_washings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/type_of_cleaning_and_washings_helper.rb
module TypeOfCleaningAndWashingsHelper
end

app/views/type_of_cleaning_and_washings/_form.html.erb
<%= simple_form_for @type_of_cleaning_and_washing, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :mem_price %>
	<%= f.input :car_id, collection: Car.all %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
		<br />
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                type_of_cleaning_and_washings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/type_of_cleaning_and_washings/edit.html.erb
<%- model_class = TypeOfCleaningAndWashing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/type_of_cleaning_and_washings/index.html.erb
<h1 class="page-header">Type of Washing Solutions</h1>

<div class="row-fluid">
  <div class="span9">
    <div>
      <h2 class="section-header">Type of Washing Solutions
        <span class="pull-right">
          <a href="#searchModal" role="button" class="btn btn-iconize" data-toggle="modal" data-btn-iconize="icon-search">
            <i class="icon-search"></i> Search
          </a>
          <a href="#newCar" class="btn btn-blue btn-iconize" data-btn-iconize="icon-plus" data-toggle="modal">Add</a>
        </span>
      </h2>

      <!-- search modal -->
      <div class="modal hide fade" id="searchModal" role="dialog">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3>Search</h3>
        </div>
        <div class="modal-body">
          <%= search_form_for @search, :html => {:class => "form-horizontal"} do |f| %>

            <div class="control-group">
              <%= f.label :name_cont, "Name", :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :name_cont  %>
              </div>
            </div>

            <div class="form-actions">
              <%= f.submit "Search", :class => "btn btn-primary" %>
              <a href="#" class="btn" data-dismiss="modal">Cancel</a>
            </div>
          <% end %>
        </div>
      </div>

      <!-- end search modal -->

      <% if @type_of_cleaning_and_washings.blank? %>

        <div class="span12">
          <p class="text-warning">No records found.</p>
        </div>
        <br/>
      
      <% else %>
      
        <table class="table table-striped table-condensed">
          <thead>
            <th>Car Type Name</th>
						<th>Price</th>
						<th>Member's price</th>
            <th></th>
          </thead>
          <tbody>
            <% @type_of_cleaning_and_washings.each do |type_of_cleaning_and_washing| %>
            <tr>
              <td><%= type_of_cleaning_and_washing.blank? ? "N/A" : type_of_cleaning_and_washing.name %></td>
							<td><%= type_of_cleaning_and_washing.blank? ? "N/A" : type_of_cleaning_and_washing.price %></td>
							<td><%= type_of_cleaning_and_washing.blank? ? "N/A" : type_of_cleaning_and_washing.mem_price %></td>
              <td>
                <span class="btn-group pull-right">
                  <a href="<%= edit_type_of_cleaning_and_washing_path(type_of_cleaning_and_washing) %>" class="hidden-480 btn btn-small btn-iconize" data-btn-iconize="icon-pencil">Edit</a>
                  
                  <%= link_to type_of_cleaning_and_washing_path(type_of_cleaning_and_washing), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'hidden-480 btn btn-small btn-danger btn-iconize',
                    :'data-btn-iconize' => 'icon-remove',
                    :title => "Delete" do%>Delete
                  <%end%>                  
                </span>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      
      <% end %>

    </div>

		<!-- new user modal -->
		<div class="modal hide fade" id="newCar" role="dialog">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		    <h3>New Type of Washing</h3>
		  </div>
		  <div class="modal-body">
		    <%= render :partial => 'form' %>
		  </div>
		</div>
		<!-- end new user modal -->
		
  </div><!--span-->
</div>

app/views/type_of_cleaning_and_washings/new.html.erb
<%- model_class = TypeOfCleaningAndWashing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/type_of_cleaning_and_washings/show.html.erb
<%- model_class = TypeOfCleaningAndWashing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @type_of_cleaning_and_washing.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @type_of_cleaning_and_washing.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mem_price) %>:</strong></dt>
  <dd><%= @type_of_cleaning_and_washing.mem_price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              type_of_cleaning_and_washings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_type_of_cleaning_and_washing_path(@type_of_cleaning_and_washing), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              type_of_cleaning_and_washing_path(@type_of_cleaning_and_washing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>