config/routes.rb
Carwash::Application.routes.draw do

  resources :memberships

  resources :cars

  get "dashboards/index"

  resources :inventories

  resources :type_of_cleaning_and_washings

  resources :customers do 
    member do
      get 'pay'
    end
    collection do 
      put 'dynamic_pricing'
      put 'dynamic_price_member'
    end
  end

  authenticated :user do
    root :to => 'dashboards#index' 
  end
  root :to => "home#index"
   
  devise_for :users do
    delete 'logout' => 'devise/sessions#destroy'
  end
  
  resources :users

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :name
  
  has_many :customers
  has_many :type_of_cleaning_and_washings
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @search = Car.ransack(params[:q])
    @cars = @search.result
    @car = Car.new
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to cars_path, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to cars_path, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for @car, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/index.html.erb
<h1 class="page-header">Cars</h1>

<div class="row-fluid">
  <div class="span9">
    <div>
      <h2 class="section-header">Cars
        <span class="pull-right">
          <a href="#searchModal" role="button" class="btn btn-iconize" data-toggle="modal" data-btn-iconize="icon-search">
            <i class="icon-search"></i> Search
          </a>
          <a href="#newCar" class="btn btn-blue btn-iconize" data-btn-iconize="icon-plus" data-toggle="modal">Add</a>
        </span>
      </h2>

      <!-- search modal -->
      <div class="modal hide fade" id="searchModal" role="dialog">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3>Search</h3>
        </div>
        <div class="modal-body">
          <%= search_form_for @search, :html => {:class => "form-horizontal"} do |f| %>

            <div class="control-group">
              <%= f.label :name_cont, "Name", :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :name_cont  %>
              </div>
            </div>

            <div class="form-actions">
              <%= f.submit "Search", :class => "btn btn-primary" %>
              <a href="#" class="btn" data-dismiss="modal">Cancel</a>
            </div>
          <% end %>
        </div>
      </div>

      <!-- end search modal -->

      <% if @cars.blank? %>

        <div class="span12">
          <p class="text-warning">No records found.</p>
        </div>
        <br/>
      
      <% else %>
      
        <table class="table table-striped table-condensed">
          <thead>
            <th>Car Type Name</th>
            <th></th>
          </thead>
          <tbody>
            <% @cars.each do |car| %>
            <tr>
              <td><%= car.blank? ? "N/A" : car.name %></td>
              <td>
                <span class="btn-group pull-right">
                  <a href="<%= edit_car_path(car) %>" class="hidden-480 btn btn-small btn-iconize" data-btn-iconize="icon-pencil">Edit</a>
                  
                  <%= link_to car_path(car), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'hidden-480 btn btn-small btn-danger btn-iconize',
                    :'data-btn-iconize' => 'icon-remove',
                    :title => "Delete" do%>Delete
                  <%end%>                  
                </span>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      
      <% end %>

    </div>

		<!-- new user modal -->
		<div class="modal hide fade" id="newCar" role="dialog">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		    <h3>New Type of Car</h3>
		  </div>
		  <div class="modal-body">
		    <%= render :partial => 'form' %>
		  </div>
		</div>
		<!-- end new user modal -->
		
  </div><!--span-->
</div>

app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @car.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cars_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>