config/routes.rb
Carwash::Application.routes.draw do

  resources :memberships

  resources :cars

  get "dashboards/index"

  resources :inventories

  resources :type_of_cleaning_and_washings

  resources :customers do 
    member do
      get 'pay'
    end
    collection do 
      put 'dynamic_pricing'
      put 'dynamic_price_member'
    end
  end

  authenticated :user do
    root :to => 'dashboards#index' 
  end
  root :to => "home#index"
   
  devise_for :users do
    delete 'logout' => 'devise/sessions#destroy'
  end
  
  resources :users

end

app/views/layouts/_footer.html.erb
<footer>        
  <p>&copy; <%= Date.today.strftime("%Y") %> Q7 Car Wash
  <span class="pull-right muted">HTML5 and CSS3 compatible web browsers recommended (eg. Firefox 4+, Chrome 10+, IE9+)</span></p>
</footer>

app/views/layouts/_sidebar.html.erb
 <div>
  <ul class="nav nav-list">
      <li <%= "class=active" if controller.controller_name == "users" %>><a href="<%= users_path%>">Users</a></li>
      <li <%= "class=active" if(controller.controller_name == "inventories") %>><a href="<%= inventories_path %>">Inventories</a></li>
			<li <%= "class=active" if(controller.controller_name == "customers") %>><a href="<%= customers_path %>">Customers</a></li>
			<li <%= "class=active" if(controller.controller_name == "cars") %>><a href="<%= cars_path %>">Type of Cars</a></li>
			<li <%= "class=active" if(controller.controller_name == "type_of_cleaning_and_washings") %>><a href="<%= type_of_cleaning_and_washings_path %>">Type of Washings</a></li>
			<li <%= "class=active" if(controller.controller_name == "memberships") %>><a href="<%= memberships_path %>">Type of Memberships</a></li>
		
  </ul>
</div>

app/views/layouts/_tabs.html.erb
<div class="primary-tabs">
  <ul class="nav nav-tabs">
     <% if user_signed_in? %>
			 <% if (current_user.has_role? "admin") %>
				<li <%= "class=active" if controller.controller_name =~ /dashboards/ %>><a href="<%= root_path %>">Dashboard</a></li>
				<li <%= "class=active" if controller.controller_name =~ /customers/ %>><a href="<%= customers_path %>">Customers</a></li>
				<li <%= "class=active" if controller.controller_name =~ /inventories/ %>><a href="<%= inventories_path %>">Inventories</a></li>
				<li <%= "class=active" if controller.controller_name =~ /type_of_cleaning_and_washings/ %>><a href="<%= type_of_cleaning_and_washings_path %>">Washing and Cleaning</a></li>
				<li <%= "class=active" if controller.controller_name =~ /memberships/ %>><a href="<%= memberships_path %>">Memberships</a></li>
			<% else %>
				<li <%= "class=active" if controller.controller_name =~ /dashboards/ %>><a href="<%= root_path %>">Dashboard</a></li>
				<li <%= "class=active" if controller.controller_name =~ /customers/ %>><a href="<%= customers_path %>">Customers</a></li>
				<li <%= "class=active" if controller.controller_name =~ /inventories/ %>><a href="<%= inventories_path %>">Inventories</a></li>
				<li <%= "class=active" if controller.controller_name =~ /type_of_cleaning_and_washings/ %>><a href="<%= type_of_cleaning_and_washings_path %>">Washing and Cleaning</a></li>
				<li <%= "class=active" if controller.controller_name =~ /memberships/ %>><a href="<%= memberships_path %>">Memberships</a></li>
			<% end %>
	 <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Carwash" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>

  <body>  
    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner navbar-inverse">      
        <div class="container-fluid">
            <%= link_to root_path, :class => "small-logo" do %><img src="/assets/Q7.jpg" alt="Logo"><%end%></img>
            <%if user_signed_in?%>
              <div class="pull-right">               
                <ul class="nav">
									<li><%= link_to customers_path do %><i class="icon-user"></i>  <%end%></li>
                  <li><%= link_to 'Login As : '+ current_user.name, edit_user_registration_path(:id => current_user) %></li>
                  <li><%= link_to logout_path, :method => :delete do %><i class="icon-off"></i> Logout <%end%></li>
                </ul>
              </div>
            <%end%>           
        </div>
      </div>
    </div>
      
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
       
          <%= render :partial => "layouts/tabs" %> 

          <div class="well-tabbed">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
      
        </div>
      </div>

      <%= render :partial => "layouts/footer" %>
    </div>   
    
    <%= yield :details_modals%>
    <%= javascript_include_tag "application" %>
    <%= yield :javascript%>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title><%= content_for?(:title) ? yield(:title) : "" %></title> 
    <%= csrf_meta_tags %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles%> 
    <link rel="shortcut icon" href="/assets/favicon.ico">  
  </head>
  <body class="landing">
    <div class="container-fluid">      
      <div class="form-signin shadowed">      
        <%= bootstrap_flash %>
        <%= link_to root_path, :class => "" do %><img src="/assets/Q7.jpg" alt="Logo"><%end%>

        <%= yield %>     
      
      </div>
      <%= render :partial => "layouts/footer" %>
    </div>

    <!-- Le Javascript -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript%>
  </body>
</html>